### ISSUE TITLE
How to install programs on machines

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#14]
Always nice to have this as reference

**Comment by WowSuchRicky** [comment]
anything other than `sudo apt-get install <package>` ? if not let's just throw it in, may as well, to start working on a "new coords" tutorial type thing.

**Comment by daguava** [comment]
I wish there was an easy way to keep an updated disk image with packages pre-installed, but it would have to be made every time a new linux version comes along.

**Comment by katamaritaco** [comment]
Yeah for adding things to cf.packages, it doesn't seem to work correctly. For example, when you input sudo apt-get install golang, it installs go v 1.2.1.  But having 'golang' in the cf.packages doesn't seem to do that...

**Comment by LOZORD** [comment]
@jdetter and @Ricky54326  is this working now?

**Comment by jdetter** [comment]
I made a script that can do this, I installed chrome, sublime text and some other packages using it and it worked perfectly. We can still use ansible if Ricky wants to use it. Ideally we would want some sort of user friendly gui for coords to use to do this sort of stuff instead of typing terminal commands. It would be cool if we had one program that would let you add new users and install packages and whatever else we need to do, that way the less technical coords would still be able to administer the lab.\

**Comment by katamaritaco** [comment]
I feel like we don't _need_ a fancy gui, coords should be able to use basic command line programs (so long as documentation is decent). A 'coord-program' with flags for all coord specific commands could be interesting, but possibly a tad crufty... 

ex of 'coord-program'

> ./coord -AddUser nheindl UW_IDNUM CS_ID Whatever_else

I feel like as long as all the 'nice files' are in the same place, and good documentation is there, that'd be fine. Open to ideas though. This should probably go to group discussion at post mortem @jdetter

**Comment by LOZORD** [comment]
:camel:

**Comment by WowSuchRicky** [comment]
This is done now. 

Steps should probably be added somewhere:
1. ssh eris
2. sudo bash
3. cd /srv/maintain/UPL-Config/scripts
4. sudo bash pkg-install.sh <pkg name>

**Comment by LOZORD** [comment]
Please either add this to the `upl-admin` script or put it in some README.

**Comment by WowSuchRicky** [comment]
Sorry for the confusion! `sudo upl-admin` can already do this without any of the steps I mentioned above, and on any machine, too.

Closing.
