### ISSUE TITLE
Fabled "UPL History" project

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#40]
An open project for anybody wanting to dig around the webs and find info on the UPL's awesome decades long history.

**Comment by spwilson2** [comment]
A good starting location..

https://web.archive.org/web/20150202141819/http://alyska.net/uplhistory/

:+1:  - Nick

**Comment by LOZORD** [comment]
Should this be its own repo?

:+1: btw

**Comment by katamaritaco** [comment]
I think that'd be up to whomever would want to proceed with the project. Might be easier to do iterative work in, and then integrate back here, but up to that person/those people

**Comment by MarshMue** [comment]
There's a LOT of gold here, I'm assuming we want to put this on the website, and if so, how should it be formatted/added to the site? I'm pretty unfamiliar with web stuff and the infrastructure of the new site.

**Comment by LOZORD** [comment]
I think putting it on the site would be crufty. Having a repo (with link from the site) would be good. Probably best just to use Markdown for now, since it is easily convertible to HTML.

Also, we should start adding to the UPL history tome at the end of every semester/year.

**Comment by katamaritaco** [comment]
Yeah putting it in its own repo would be nice for now (and maybe for all time). :+1: for that

**Comment by MarshMue** [comment]
Anyone know of any more places for history? The above link has a lot of stuff from a pretty specific time period. I think we have an email list for alum right? Would be nice if I could send out an email to people to ask for their recollections.

**Comment by katamaritaco** [comment]
Yeah we do, but it might also be worth crawling through old lists and crawling through google/linkedin/facebook to find them and ask them.

It'd be worth it to make a nice draft of what you'll send to everybody (for all of us to review) and then send it off. For example, it'd be great to know where they've worked since, what they've done, and what UPL means to them.

**Comment by spwilson2** [comment]
Also... https://youtu.be/AZH_21AeF0A

Yeah we do, but it might also be worth crawling through old lists and
crawling through google/linkedin/facebook to find them and ask them.

It'd be worth it to make a nice draft of what you'll send to everybody (for
all of us to review) and then send it off. For example, it'd be great to
know where they've worked since, what they've done, and what UPL means to
them.

**Comment by mjneil** [comment]
If we are going to compile our own history doc, we should also link to any original sources of our information if someone else is hosting it I feel just to give credit to the past UPL'ers that are providing that info. Thoughts?

**Comment by WowSuchRicky** [comment]
Any update on this?

**Comment by MarshMue** [comment]
Not yet, just got done with a busy week for me school wise so I should make some decent progress in the coming week. @mjneil I already attributed the one source I have so far :3 I'll share a draft email probably sometime in the next few days.

**Comment by MikeCook9994** [comment]
I want in on this with you Marshall. I'd love to work to compile the history of the upl and write ours for future coords.

**Comment by MarshMue** [comment]
Anyone can work on this! I've personally been distracted by some side projects of mine since I've had rare inspiration to work on them, so apologies for lack of progress. I think this, at least to what I've thought, would just be like a wiki history section about the UPL (btw I created a directory for it), that would just read like a history book about the UPL. 

I was talking about this with @Ricky54326, and maybe it's been discussed about on facebook, but it would be sweet if we had a place for Alumni to list contact information, what they're currently doing, what they've done and whether they are ok with UPLers contacting them, maybe to network about a company they are interested, or something they had done that interested them. We were thinking that this could just be something in github, maybe a github page, that anyone could contribute to, so any past UPLer could just update their own info, and we could just provide an easy interface for them to use.

Thoughts?

**Comment by WowSuchRicky** [comment]
+1 ^ . Definitely something easy enough to edit right on github with a PR to add yourself to it later on/when you graduate. We can send reminders at the end of every academic year asking UPLers to register themselves on there and where they'll be working and whatnot if they want to stay in touch. We can add them to the upl-alumni mailing list as well. 

As far as history goes, I don't particularly have interest in working on it but I think the actual contact info can literally just be an .md file.

**Comment by LOZORD** [comment]
Yeah, I think a basic markdown table for UPL Alumni/Past Coords would be
cool.

**Comment by MikeCook9994** [comment]
Any movement on this? There's a past coord here at Microsoft who told me so much cool stuff and I have a feeling he'd be willing to contribute it.

**Comment by LOZORD** [comment]
@MikeCook9994, see for yourself: https://github.com/UW-UPL/History

1) The past coord can totally add stuff (either directly or through you).
2) We can close this issue now and add any related issues to the History repo itself.

**Comment by spwilson2** [comment]
Closing per @LOZORD 

@MikeCook9994 feel free to open a separate issue on the History project if you need to.
