### ISSUE TITLE
How to restart mpd on chiptunes?

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Documentation#54]
How does one do this? Currently getting a `problems setting volume` error.

**Comment by WowSuchRicky** [comment]
What command are you getting this error from? Also, if mpd is a service, try `sudo service mpd restart`

**Comment by LOZORD** [comment]
Basically, `pianobar` works fine but `ncmpcpp` (and I _think_ by extension,
`mpd`) does not.

**Comment by katamaritaco** [comment]
Yeah there is some weird issue with pulses as well I think within mpd.

**Comment by LOZORD** [comment]
Is chiptunes kill? Is there still a music server?

**Comment by LOZORD** [comment]
@MarshMue or anyone who helped with the new machines, did we retire or modify chiptunes?

**Comment by ChristianBorst** [comment]
Fixed the mpd issue, ncmpcpp on chiptunes is working again.

Note for future issues regarding mpd: 
Looking at the log file /var/log/mpd/mpd.log revealed that mpd didn't have access to /home/mpd/.config/pulse since even /home/mpd didn't exist. Creating the folders and chown-ing to give the user mpd access is what fixed the problem. Then restarting mpd (kill the process then restart it) fixed the issue.

Let there be tunes!
